### PR TITLE
Feature/12

### PR DESCRIPTION
**Pull request by evanbutera**
Partial update to allow webfonts as options.

#12

### CODE REVIEW

**Comment by BrianDGLS** [comment]
Thanks Evan!

Before I pull this down to test I'll need you to update the `Main.ts` file, compile it, and then commit it along with the `.js` file that it produced.

The app is written in Typescript which is then compiled to js. So only the `.ts` files should be worked on.

If this is an issue just email me and let me know.

Regards,

Brian

**Comment by evanbutera** [comment]
Updated `.ts` file, sorry for the mistake.
should be ok now.

E.

**Comment by BrianDGLS** [comment]
Thanks.

Code looks good, will test in the morning and hopefully merge.

**Comment by BrianDGLS** [comment]
@evanbutera Merged to develop, nice work!

**Pull request merged**
